### ISSUE TITLE
No Vulnerabilities in Results 

### ISSUE THREAD

**Issue by KathanP19** [m4ll0k/Shodanfy.py#1]
`$ echo "67.225.165.209" | python3 ~/Desktop/autoreco/tools/Shodanfy.py/shodanfy.py --stdin --getinfo`
```
[+] IP: 67.225.165.209
[+] Get info...
	Country -> United States
	Organization -> Liquid Web, L.L.C
	ISP -> Liquid Web, L.L.C
	Last Update -> 2020-05-28T23:43:57.105259
	Hostnames -> kameleon.nulldata.xyz
	ASN -> AS32244
root@kali:~# 
```

I even tried the --getvuln option. I think the api key is necessary for vulnerability scanning.

**Comment by KathanP19** [comment]
It worked , had some issue in my system.

**Comment by arjundarkweb** [comment]
I tried the same command here it is
echo "65.225.165.209" |python3 shodanfy.py --stdin --getinfo
but i m not getting result
